version: '3.9'

networks:
  default:
    name: proxy
    external: true

services:
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: 'zabbix'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbiz'
      MYSQL_ROOT_PASSWORD: 'zabbix'


  server:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      DB_SERVER_HOST: 'mysql'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix'
    ports:
      - "10051:10051"

  web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      DB_SERVER_HOST: 'postgres'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_DB: 'zabbix'
      ZBX_SERVER_HOST: 'server'
      PHP_TZ: 'America/Maceio'
#    ports:
#      - "80:8080"

  agent:
    image: zabbix/zabbix-agent:latest
    environment:
      ZBX_HOSTNAME: 'zabbixserver' #Esta env configura a opção HOSTNAME no zabbix_agentd.conf
      ZBX_SERVER_HOST: 'server'
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: 'server'
#      ZBX_HOSTINTERFACE: 'agent'
