version: '3.9'

networks:
  proxy:
    name: proxy
    external: true

services:
  postgres:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_DB: 'zabbix'
    networks:
      - proxy

  server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_HOST: 'postgres'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_DB: 'zabbix'
    ports:
      - "10051:10051"
    networks:
      - proxy

  web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      DB_SERVER_HOST: 'postgres'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_DB: 'zabbix'
      ZBX_SERVER_HOST: 'server'
      PHP_TZ: 'America/Maceio'
#    ports:
#      - "80:8080"
    networks:
      - proxy

  agent:
    image: zabbix/zabbix-agent:latest
    environment:
      ZBX_HOSTNAME: 'Zabbix server' # qual a finalidade dessa env?
      ZBX_SERVER_HOST: 'server'
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: 'server'
#      ZBX_HOSTINTERFACE: 'agent'
    networks:
      - proxy
