version: '3.9'

networks:
  default:
    name: proxy
    external: true

services:
  mysql:
    image: mysql:8.3
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--log-bin-trust-function-creators=1']
    environment:
      MYSQL_DATABASE: 'zabbix'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix'
      MYSQL_ROOT_PASSWORD: 'zabbix'

  server:
    image: zabbix/zabbix-server-mysql:7.0.0-alpine
    environment:
#      ZBX_DEBUGLEVEL: '3'
      DB_SERVER_DBNAME: 'zabbix'
      DB_SERVER_HOST: 'mysql'
      DB_SERVER_PORT: '3306'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix'
    ports:
      - "10051:10051"

#  web:
#    image: zabbix/zabbix-web-nginx-mysql:7.0.0-alpine
#    environment:
#      DB_SERVER_DBNAME: 'zabbix'
#      DB_SERVER_HOST: 'mysql'
#      DB_SERVER_PORT: '3306'
#      MYSQL_USER: 'zabbix'
#      MYSQL_PASSWORD: 'zabbix'
#      ZBX_SERVER_HOST: 'server'
#      PHP_TZ: 'America/Maceio'
#      ZBX_UPLOADMAXFILESIZE: '50M'
##      ZBX_POSTMAXSIZE: '500M'
#      ZBX_MEMORYLIMIT: '350M'


  web:
    image: zabbix/zabbix-web-apache-mysql:7.0.0-alpine
    environment:
      DB_SERVER_DBNAME: 'zabbix'
      DB_SERVER_HOST: 'mysql'
      DB_SERVER_PORT: '3306'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix'
      ZBX_SERVER_HOST: 'server'
      PHP_TZ: 'America/Maceio'
      ZBX_UPLOADMAXFILESIZE: '50M'
#      ZBX_POSTMAXSIZE: '500M'
      ZBX_MEMORYLIMIT: '350M'

  agent:
#    image: zabbix/zabbix-agent:7.0.0-alpine
    image: zabbix/zabbix-agent:alpine-5.0.0
    environment:
      ZBX_HOSTNAME: 'zabbixserver' #Esta env configura a opção HOSTNAME no zabbix_agentd.conf
      ZBX_SERVER_HOST: 'server'
      ZBX_SERVER_PORT: '10051'
#      ZBX_ACTIVESERVERS: 'server:10051'
#      ZBX_HOSTINTERFACE: 'zabbixserver'
