version: '3.9'

networks:
  default:
    name: proxy
    external: true

services:
  postgres:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_DB: 'zabbix'

  server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_DBNAME: 'zabbix'
      DB_SERVER_HOST: 'postgres'
      DB_SERVER_PORT: '5432'
#      DB_SERVER_SCHEMA: 'public'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_DB: 'zabbix'
    ports:
      - "10051:10051"

  web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      DB_SERVER_DBNAME: 'zabbix'
      DB_SERVER_HOST: 'postgres'
      DB_SERVER_PORT: '5432'
#      DB_SERVER_SCHEMA: 'public'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_DB: 'zabbix'
      ZBX_SERVER_HOST: 'server'
      PHP_TZ: 'America/Maceio'
#    ports:
#      - "80:8080"

  agent:
    image: zabbix/zabbix-agent:latest
    environment:
      ZBX_HOSTNAME: 'zabbixserver' #Esta env configura a opção HOSTNAME no zabbix_agentd.conf
      ZBX_SERVER_HOST: 'server'
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: 'server'
#      ZBX_HOSTINTERFACE: 'agent'
