Vagrant.configure("2") do |k8|
  k8.vm.define "master" do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "master"
#    config.vm.network "public_network", bridge: "enp0s13f0u1", type: "dhcp"
    config.vm.network "public_network", bridge: "wlp0s20f3", type: "dhcp"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "Master"
      vbox.memory = 4096
      vbox.cpus = 2
    end
  end
  k8.vm.define "worker" do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "worker"
#    config.vm.network "public_network", bridge: "enp0s13f0u1", type: "dhcp"
    config.vm.network "public_network", bridge: "wlp0s20f3", type: "dhcp"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "Worker"
      vbox.memory = 4096
      vbox.cpus = 2
    end
  end
end
