version: '3.9'

#networks:
#  default:
#    name: apache_reverso
#    external: true

services:
  gitlab:
    image: gitlab/gitlab-ce:17.0.3-ce.0
#    image: gitlab/gitlab-ce:17.1.1-ce.0
    ports:
      - "80:80" 
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://localhost'"

  runner:
    image: gitlab/gitlab-runner:alpine3.19
