version: '3.9'

networks:
  proxy:
    name: proxy
    external: true

services:
  nginx:
    image: nginx:1.27.0-alpine3.19-perl 
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - proxy
