server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# - job_name: system
#   pipeline_stages:
#   static_configs:
#   - targets:
#      - loki
#     labels:
#      job: varlogs  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
#      host: yourhost # A `host` label will help identify logs from this machine vs others
#      __path__: /var/log/*.log
 - job_name: CONTAINERS
#   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: containerlogs  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
      __path__: /var/lib/docker/containers/*/*log

   pipeline_stages:

   - json:
       expressions:
         stream: stream
         attrs: attrs
         tag: attrs.tag
 
   - regex:
       expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
       source: "tag"
 
   - labels:
       tag:
       stream:
       image_name:
       container_name:
       image_id:
       container_id:
