version: '3.9'
  
services:
  open:
    image: openproject/openproject:14.1.1
    environment:
      OPENPROJECT_SECRET_KEY_BASE: 'secret'
      OPENPROJECT_HOST__NAME: 'open:8080'
      OPENPROJECT_HTTPS: 'false'
      OPENPROJECT_DEFAULT__LANGUAGE: 'en'
    ports:
      - "8080:80"
