version: '3.9'

networks:
  default:
    name: proxy
    external: true

services:
  proxy:
    image: httpd:2.4.59-alpine
    ports:
      - "81:80"
  ubuntu:
    image: proxy:01
#    command: ['sh', '-c', 'sleep infinity']
    ports:
      - "80:80"
