- name: Playbook Master
  hosts: master
  user: vagrant
  tasks:
#   - name: Update Packages
#     become: true
#     become_user: root
#     apt:
#       update_cache: yes
#   - name: br_netfilter - Load the module
#     ansible.builtin.shell: sudo modprobe br_netfilter
   - name: br_netfilter - Create the new kernel parameters
     ansible.builtin.shell: |
       echo master > teste.txt
#       cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf \n
#       br_netfilter
#       EOF
#       cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf \n
#       net.bridge.bridge-nf-call-ip6tables = 1
#       net.bridge.bridge-nf-call-iptables = 1
#       EOF
#       sudo sysctl --system
#   - name: Docker - Install packages to allow apt to use a repository over HTTPS
#     become: true
#     become_user: root
#     ansible.builtin.package:
#       name:
#         - ca-certificates
#         - curl
#         - gnupg
#         - lsb-release
#       state: latest
#   - name: Docker - Add Docker’s official GPG key
#     ansible.builtin.shell: |
#       sudo mkdir -p /etc/apt/keyrings
#       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
#   - name: Docker - Add Docker’s official GPG key
#     ansible.builtin.shell: |
#       echo \
#       "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
#        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#   - name: Docker - Update Repository
#     ansible.builtin.shell: |
#       sudo apt update
#   - name: Docker - Install
#     become: true
#     become_user: root
#     ansible.builtin.package:
#       name:
#         - docker-ce
#         - docker-ce-cli
#         - containerd.io
#         - docker-compose-plugin
#       state: latest
#   - name: Kubernetes - packages needed to use the Kubernetes 
#     become: true
#     become_user: root
#     ansible.builtin.package:
#       name:
#         - apt-transport-https
#         - ca-certificates
#         - curl
#       state: latest
#   - name: Kubernetes - Download the Google Cloud public signing key 
#     ansible.builtin.shell: |
#       sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
#   - name: Kubernetes - Add the Kubernetes apt repository
#     ansible.builtin.shell: |
#       echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
#   - name: Kubernetes - Update Packages
#     become: true
#     become_user: root
#     apt:
#       update_cache: yes
#   - name: Kubernetes - Install
#     become: true
#     become_user: root
#     ansible.builtin.package:
#       name:
#         - kubelet
#         - kubeadm
#         - kubectl
#   - name: Kubernetes - Download the Google Cloud public signing key 
#     ansible.builtin.shell: |
#       sudo apt-mark hold kubelet kubeadm kubectl
